version: "3"
services:
    api:
        container_name: intelnetus-api
        build: ./intelnetus-api/
        ports:
            - '5000:5000'
        volumes:
            - ./../../DockerVolumes/.pybliometrics:/app/.pybliometrics
        networks:
            - intelnetus
    
    ui:
        container_name: intelnetus-ui
        build: ./intelnetus-ui/
        ports:
            - '4200:4200'
        networks:
            - intelnetus

networks:
    intelnetus:
        driver: bridge